---
# =============================================================================
# Install Oracle GI 19.3.0 Software Only:
# (1) Install Oracle GI 19.3.0 Software Only in Silent Mode
# (2) Validate output logs 
# =============================================================================
- name: Install Oracle 19c GI Software
  when: inventory_hostname in groups['ora-x1']
  remote_user: "{{ root_user }}"
  become: yes
  become_user: "{{ grid_user }}"
  shell: "{{ grid_home }}/gridSetup.sh -silent -ignorePrereqFailure -waitforcompletion -skipStackCheck -responseFile {{ stage_dir }}/{{ gi_rspfile }} > /u02/stage/giinstalloutput.log"
  args:
      warn: false # set warn=false to prevent warning
  failed_when: racgisoft_install_result.rc != 6   #### This condition is based on my own setup
  register: racgisoft_install_result
  no_log:             true

- name: Get the output log status
  remote_user: "{{ root_user }}"
  become: yes
  become_user: oracle
  when: inventory_hostname in groups['ora-x1']
  shell: grep -r "Successfully Setup Software with *" /u02/stage/giinstalloutput.log
  register: racgisoftinstall_log

- name: "Output from Post GI Software Installation Check"
  debug:
    var: racgisoftinstall_log.stdout
    verbosity: 0
  when: inventory_hostname in groups['ora-x1'] and "'Successfully Setup Software.' or 'Successfully Setup Software with warning(s).' in racgisoftinstall_log.stdout"
